# 1) to start postgreSQL : brew services start postgresql@16
# 2) to stop postgreSQL : brew services stop postgresql@16
# 3) Workflow : JSON file → PostgreSQL tables → SQL queries → Flask display

import psycopg

# Connect to the database we created
connection = psycopg.connect(
    dbname = "studentCourses",
    user = "postgres"
)

# Open a cursor to perform database operationis
with connection.cursor() as cur:
    
    # Execute our Select all command
    cur.execute(
        """
        CREATE TABLE courses(
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT
        )
        """
    )
    
    cur.execute(
        """
        CREATE TABLE studentCourses(
            studentID int,
            courseID int
        )
        """
    )

    cur.execute(
        """
        INSERT INTO courses(id, name)
            VALUES (1, 'SQL Server'), (2, 'ASP.NET MVC'), (3, 'MongoDB'), (4, 'Java'), (5, 'PHP');
            
        """
    )    
    
    cur.execute(
        """
        INSERT INTO studentCourses(studentID, courseID)
            VALUES (1,1), (1,2), (1,3), (2,3), (2,4), (3,3), (3,5);
            
        """
    ) 
    connection.commit()
cur.close()
connection.close()


with connection.coursor() as cur:
    # execute our Select all command
    cur.execute("""
        select * from courses;
        """)
     
    #print outputs
    print(cur.fetchall())
    
    cur.execute("""
        select * from studentCourses
        """)
    
    #print output
    print(cur.fetchall())
    
    connection.commit()
cur.close()
connection.close()



#######################################


